		export const SKINS = [
			{
				id: "abyss",
				colorScheme: "dark",
				tokens: {
					"--dsw-alias-bg-base": "#060a14",
					"--dsw-alias-bg-layer-1": "#0d1424",
					"--dsw-alias-bg-layer-2": "#141e36",
					"--dsw-alias-bg-layer-3": "#1a2744",
					"--dsw-alias-bg-overlay": "#1b2947",
					"--dsw-alias-border-l1": "rgba(148, 168, 210, 0.13)",
					"--dsw-alias-border-l2": "rgba(148, 168, 210, 0.24)",
					"--dsw-alias-label-primary": "#eef2fa",
					"--dsw-alias-label-secondary": "#9fb2d4",
					"--dsw-alias-label-tertiary": "#788eb6",
					"--dsw-alias-brand-primary": "#4f83f2",
					"--dsw-alias-brand-text": "#ffffff",
					"--dsw-alias-button-primary-hover": "#6f9af6",
					"--dsw-alias-button-primary-dimmed": "#141e36",
					"--dsw-alias-state-business-primary": "#4f83f2",
					"--dsw-alias-state-business-tertiary": "#141e36",
					"--dsw-alias-interactive-bg-hover": "rgba(79, 131, 242, 0.13)",
					"--dsw-alias-interactive-bg-active": "rgba(79, 131, 242, 0.22)",
					"--dsw-alias-markdown-code-block": "#0b1120",
					"--dsw-alias-markdown-inline-code": "#141e36",
					"--dsw-specific-sidebar-fill": "#0b1120",
					"--dsw-specific-sidebar-nav-item-active": "#141e36",
					"--dsw-specific-sidebar-nav-item-hover": "#101828",
					"--dsw-alias-scrollbar-bg-l1": "#1a2744",
					"--dsw-alias-scrollbar-bg-l2": "#1f2f52",
					"--dsw-alias-scrollbar-hover-l1": "#26375f",
					"--dsw-alias-scrollbar-hover-l2": "#26375f"
				}
			},
			{
				id: "aurora",
				colorScheme: "dark",
				tokens: {
					"--dsw-alias-bg-base": "#04120f",
					"--dsw-alias-bg-layer-1": "#0a1d18",
					"--dsw-alias-bg-layer-2": "#102a23",
					"--dsw-alias-bg-layer-3": "#16372e",
					"--dsw-alias-bg-overlay": "#183a31",
					"--dsw-alias-border-l1": "rgba(110, 231, 183, 0.12)",
					"--dsw-alias-border-l2": "rgba(110, 231, 183, 0.22)",
					"--dsw-alias-label-primary": "#eafaf2",
					"--dsw-alias-label-secondary": "#92d5b8",
					"--dsw-alias-label-tertiary": "#6fb398",
					"--dsw-alias-brand-primary": "#34d399",
					"--dsw-alias-brand-text": "#03211a",
					"--dsw-alias-button-primary-hover": "#57e0b0",
					"--dsw-alias-button-primary-dimmed": "#102a23",
					"--dsw-alias-state-business-primary": "#34d399",
					"--dsw-alias-state-business-tertiary": "#102a23",
					"--dsw-alias-interactive-bg-hover": "rgba(52, 211, 153, 0.13)",
					"--dsw-alias-interactive-bg-active": "rgba(52, 211, 153, 0.22)",
					"--dsw-alias-markdown-code-block": "#081712",
					"--dsw-alias-markdown-inline-code": "#102a23",
					"--dsw-specific-sidebar-fill": "#081712",
					"--dsw-specific-sidebar-nav-item-active": "#102a23",
					"--dsw-specific-sidebar-nav-item-hover": "#0c231c",
					"--dsw-alias-scrollbar-bg-l1": "#16372e",
					"--dsw-alias-scrollbar-bg-l2": "#1b4438",
					"--dsw-alias-scrollbar-hover-l1": "#225344",
					"--dsw-alias-scrollbar-hover-l2": "#225344"
				}
			},
			{
				id: "nebula",
				colorScheme: "dark",
				tokens: {
					"--dsw-alias-bg-base": "#0f0a1c",
					"--dsw-alias-bg-layer-1": "#17102b",
					"--dsw-alias-bg-layer-2": "#1f1638",
					"--dsw-alias-bg-layer-3": "#271c46",
					"--dsw-alias-bg-overlay": "#291e49",
					"--dsw-alias-border-l1": "rgba(216, 180, 254, 0.12)",
					"--dsw-alias-border-l2": "rgba(216, 180, 254, 0.22)",
					"--dsw-alias-label-primary": "#f4eefc",
					"--dsw-alias-label-secondary": "#c6aee6",
					"--dsw-alias-label-tertiary": "#a28dc7",
					"--dsw-alias-brand-primary": "#a78bfa",
					"--dsw-alias-brand-text": "#150c26",
					"--dsw-alias-button-primary-hover": "#bca7fd",
					"--dsw-alias-button-primary-dimmed": "#1f1638",
					"--dsw-alias-state-business-primary": "#a78bfa",
					"--dsw-alias-state-business-tertiary": "#1f1638",
					"--dsw-alias-interactive-bg-hover": "rgba(167, 139, 250, 0.14)",
					"--dsw-alias-interactive-bg-active": "rgba(167, 139, 250, 0.24)",
					"--dsw-alias-markdown-code-block": "#130c22",
					"--dsw-alias-markdown-inline-code": "#1f1638",
					"--dsw-specific-sidebar-fill": "#130c22",
					"--dsw-specific-sidebar-nav-item-active": "#1f1638",
					"--dsw-specific-sidebar-nav-item-hover": "#191230",
					"--dsw-alias-scrollbar-bg-l1": "#271c46",
					"--dsw-alias-scrollbar-bg-l2": "#312356",
					"--dsw-alias-scrollbar-hover-l1": "#3a2c66",
					"--dsw-alias-scrollbar-hover-l2": "#3a2c66"
				}
			},
			{
				id: "ember",
				colorScheme: "dark",
				tokens: {
					"--dsw-alias-bg-base": "#120a08",
					"--dsw-alias-bg-layer-1": "#1b120e",
					"--dsw-alias-bg-layer-2": "#241913",
					"--dsw-alias-bg-layer-3": "#2d1f18",
					"--dsw-alias-bg-overlay": "#2f211a",
					"--dsw-alias-border-l1": "rgba(253, 186, 116, 0.12)",
					"--dsw-alias-border-l2": "rgba(253, 186, 116, 0.22)",
					"--dsw-alias-label-primary": "#fdf1e7",
					"--dsw-alias-label-secondary": "#d6ab8c",
					"--dsw-alias-label-tertiary": "#b68a6c",
					"--dsw-alias-brand-primary": "#fb923c",
					"--dsw-alias-brand-text": "#24110a",
					"--dsw-alias-button-primary-hover": "#fdad6a",
					"--dsw-alias-button-primary-dimmed": "#241913",
					"--dsw-alias-state-business-primary": "#fb923c",
					"--dsw-alias-state-business-tertiary": "#241913",
					"--dsw-alias-interactive-bg-hover": "rgba(251, 146, 60, 0.14)",
					"--dsw-alias-interactive-bg-active": "rgba(251, 146, 60, 0.24)",
					"--dsw-alias-markdown-code-block": "#160e0a",
					"--dsw-alias-markdown-inline-code": "#241913",
					"--dsw-specific-sidebar-fill": "#160e0a",
					"--dsw-specific-sidebar-nav-item-active": "#241913",
					"--dsw-specific-sidebar-nav-item-hover": "#1e1510",
					"--dsw-alias-scrollbar-bg-l1": "#2d1f18",
					"--dsw-alias-scrollbar-bg-l2": "#3a281d",
					"--dsw-alias-scrollbar-hover-l1": "#473225",
					"--dsw-alias-scrollbar-hover-l2": "#473225"
				}
			},
			{
				id: "midnight",
				colorScheme: "dark",
				tokens: {
					"--dsw-alias-bg-base": "#000000",
					"--dsw-alias-bg-layer-1": "#0b0b0f",
					"--dsw-alias-bg-layer-2": "#141419",
					"--dsw-alias-bg-layer-3": "#1c1c23",
					"--dsw-alias-bg-overlay": "#1d1d24",
					"--dsw-alias-border-l1": "rgba(255, 255, 255, 0.06)",
					"--dsw-alias-border-l2": "rgba(255, 255, 255, 0.12)",
					"--dsw-alias-label-primary": "#e8e8ee",
					"--dsw-alias-label-secondary": "#9d9daa",
					"--dsw-alias-label-tertiary": "#7c7c88",
					"--dsw-alias-brand-primary": "#7c8cff",
					"--dsw-alias-brand-text": "#05050a",
					"--dsw-alias-button-primary-hover": "#9aa7ff",
					"--dsw-alias-button-primary-dimmed": "#141419",
					"--dsw-alias-state-business-primary": "#7c8cff",
					"--dsw-alias-state-business-tertiary": "#141419",
					"--dsw-alias-interactive-bg-hover": "rgba(124, 140, 255, 0.13)",
					"--dsw-alias-interactive-bg-active": "rgba(124, 140, 255, 0.22)",
					"--dsw-alias-markdown-code-block": "#08080b",
					"--dsw-alias-markdown-inline-code": "#141419",
					"--dsw-specific-sidebar-fill": "#08080b",
					"--dsw-specific-sidebar-nav-item-active": "#141419",
					"--dsw-specific-sidebar-nav-item-hover": "#0e0e13",
					"--dsw-alias-scrollbar-bg-l1": "#1c1c23",
					"--dsw-alias-scrollbar-bg-l2": "#26262f",
					"--dsw-alias-scrollbar-hover-l1": "#31313c",
					"--dsw-alias-scrollbar-hover-l2": "#31313c"
				}
			},
			{
				id: "ivory",
				colorScheme: "light",
				tokens: {
					"--dsw-alias-bg-base": "#f7f4ee",
					"--dsw-alias-bg-layer-1": "#ffffff",
					"--dsw-alias-bg-layer-2": "#f0ead8",
					"--dsw-alias-bg-layer-3": "#e7dfcb",
					"--dsw-alias-bg-overlay": "#fffdf8",
					"--dsw-alias-border-l1": "rgba(122, 96, 44, 0.1)",
					"--dsw-alias-border-l2": "rgba(122, 96, 44, 0.18)",
					"--dsw-alias-label-primary": "#2e2920",
					"--dsw-alias-label-secondary": "#6f6656",
					"--dsw-alias-label-tertiary": "#8d8373",
					"--dsw-alias-brand-primary": "#a16207",
					"--dsw-alias-brand-text": "#ffffff",
					"--dsw-alias-button-primary-hover": "#c67c0f",
					"--dsw-alias-button-primary-dimmed": "#f0ead8",
					"--dsw-alias-state-business-primary": "#a16207",
					"--dsw-alias-state-business-tertiary": "#f0ead8",
					"--dsw-alias-interactive-bg-hover": "rgba(161, 98, 7, 0.08)",
					"--dsw-alias-interactive-bg-active": "rgba(161, 98, 7, 0.14)",
					"--dsw-alias-markdown-code-block": "#f0ead8",
					"--dsw-alias-markdown-inline-code": "#ece5d2",
					"--dsw-specific-sidebar-fill": "#f0ead8",
					"--dsw-specific-sidebar-nav-item-active": "#e7dfcb",
					"--dsw-specific-sidebar-nav-item-hover": "#ece4d0",
					"--dsw-alias-scrollbar-bg-l1": "#e0d6bd",
					"--dsw-alias-scrollbar-bg-l2": "#d8ccb0",
					"--dsw-alias-scrollbar-hover-l1": "#cdbfa0",
					"--dsw-alias-scrollbar-hover-l2": "#cdbfa0"
				}
			},
			{
				id: "mist",
				colorScheme: "light",
				tokens: {
					"--dsw-alias-bg-base": "#f0f3f7",
					"--dsw-alias-bg-layer-1": "#ffffff",
					"--dsw-alias-bg-layer-2": "#e7edf4",
					"--dsw-alias-bg-layer-3": "#dbe4ee",
					"--dsw-alias-bg-overlay": "#ffffff",
					"--dsw-alias-border-l1": "rgba(51, 65, 85, 0.1)",
					"--dsw-alias-border-l2": "rgba(51, 65, 85, 0.18)",
					"--dsw-alias-label-primary": "#1e293b",
					"--dsw-alias-label-secondary": "#64748b",
					"--dsw-alias-label-tertiary": "#94a3b8",
					"--dsw-alias-brand-primary": "#2563eb",
					"--dsw-alias-brand-text": "#ffffff",
					"--dsw-alias-button-primary-hover": "#3b82f6",
					"--dsw-alias-button-primary-dimmed": "#e7edf4",
					"--dsw-alias-state-business-primary": "#2563eb",
					"--dsw-alias-state-business-tertiary": "#e7edf4",
					"--dsw-alias-interactive-bg-hover": "rgba(37, 99, 235, 0.08)",
					"--dsw-alias-interactive-bg-active": "rgba(37, 99, 235, 0.14)",
					"--dsw-alias-markdown-code-block": "#e7edf4",
					"--dsw-alias-markdown-inline-code": "#dbe4ee",
					"--dsw-specific-sidebar-fill": "#e7edf4",
					"--dsw-specific-sidebar-nav-item-active": "#dbe4ee",
					"--dsw-specific-sidebar-nav-item-hover": "#e2e9f2",
					"--dsw-alias-scrollbar-bg-l1": "#cbd5e1",
					"--dsw-alias-scrollbar-bg-l2": "#c1ccda",
					"--dsw-alias-scrollbar-hover-l1": "#b4c0d0",
					"--dsw-alias-scrollbar-hover-l2": "#b4c0d0"
				}
			},
			{
				id: "rose",
				colorScheme: "light",
				tokens: {
					"--dsw-alias-bg-base": "#fbf3f5",
					"--dsw-alias-bg-layer-1": "#ffffff",
					"--dsw-alias-bg-layer-2": "#f7e4ea",
					"--dsw-alias-bg-layer-3": "#f0d2dc",
					"--dsw-alias-bg-overlay": "#fffdfd",
					"--dsw-alias-border-l1": "rgba(190, 90, 120, 0.1)",
					"--dsw-alias-border-l2": "rgba(190, 90, 120, 0.18)",
					"--dsw-alias-label-primary": "#3a2230",
					"--dsw-alias-label-secondary": "#90647a",
					"--dsw-alias-label-tertiary": "#a47d92",
					"--dsw-alias-brand-primary": "#e11d78",
					"--dsw-alias-brand-text": "#ffffff",
					"--dsw-alias-button-primary-hover": "#ec4a96",
					"--dsw-alias-button-primary-dimmed": "#f7e4ea",
					"--dsw-alias-state-business-primary": "#e11d78",
					"--dsw-alias-state-business-tertiary": "#f7e4ea",
					"--dsw-alias-interactive-bg-hover": "rgba(225, 29, 120, 0.08)",
					"--dsw-alias-interactive-bg-active": "rgba(225, 29, 120, 0.15)",
					"--dsw-alias-markdown-code-block": "#f7e4ea",
					"--dsw-alias-markdown-inline-code": "#f0d2dc",
					"--dsw-specific-sidebar-fill": "#f7e4ea",
					"--dsw-specific-sidebar-nav-item-active": "#f0d2dc",
					"--dsw-specific-sidebar-nav-item-hover": "#f4dae2",
					"--dsw-alias-scrollbar-bg-l1": "#eccfd9",
					"--dsw-alias-scrollbar-bg-l2": "#e5c0cd",
					"--dsw-alias-scrollbar-hover-l1": "#d9afbf",
					"--dsw-alias-scrollbar-hover-l2": "#d9afbf"
				}
			}
		];
